version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ../../postgres:/var/lib/postgresql/data
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - "db"
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ../:/app
    container_name: website_api
    command: python3 main.py
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}

volumes:
  website_api_data: {}

networks:
  default:
    external:
      name: sales-helper-network
