version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: db
    ports:
      - "5432:5432"
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - "db"
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ../:/app
    container_name: website_api
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
    stdin_open: true # für pdb
    tty: true # für pdb

volumes:
  website_api_data: {}

networks:
  default:
    name: mongodb_network
