version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${POSTGRES_DB}


  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - "db"
    ports:
      - "5001:5001"
    volumes:
      - ../:/app
    container_name: website_api

volumes:
  website_api_data: {}

networks:
  default:
    name: mongodb_network
