version: '3.1'
services:
  test_postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_client_api
    container_name: test_postgres
  test_web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - "test_postgres"
    volumes:
      - ../:/app
    container_name: test_website_api
    command: python3 runtests.py
    environment:
      - DB_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_client_api
      - DB_HOST=test_postgres
